- name: "Creating configMap {{ configmap_name }} on {{ target_hosts }} host group"
  hosts: "{{ target_hosts }}"
  connection: local
  tasks:
  - name: "Install cluster-proxy addon for {{ hostvars[inventory_hostname].cluster_name }}"
    ocmplus.cm.managedcluster_addon:
      hub_kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"
      managed_cluster: "{{ hostvars[inventory_hostname].cluster_name }}"
      addon_name: "cluster-proxy"
      wait: True
      timeout: 180		
  - name: "Get ClusterProxy URL for {{ hostvars[inventory_hostname].cluster_name }}"
    ocmplus.cm.cluster_proxy:
      hub_kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"
      managed_cluster: "{{ hostvars[inventory_hostname].cluster_name }}"
      wait: True
      timeout: 60
    register: cluster_proxy
  - name: debug
    debug:
      msg: "{{ cluster_proxy.cluster_url }}"
  - name: "Install managed-serviceaccount addon for {{ hostvars[inventory_hostname].cluster_name }}"
    ocmplus.cm.managedcluster_addon:
      hub_kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"
      managed_cluster: "{{ hostvars[inventory_hostname].cluster_name }}"
      addon_name: "managed-serviceaccount"
      wait: True
      timeout: 120
  - name: "Get managed ServiceAccount token for {{ hostvars[inventory_hostname].cluster_name }}"
    ocmplus.cm.managed_serviceaccount:
      hub_kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"
      managed_cluster: "{{ hostvars[inventory_hostname].cluster_name }}"
      generate_name: "managed-serviceaccount-"
      wait: True
      timeout: 60
    register: managed_serviceaccount
  - name: debug
    debug:
      msg: "token length: {{ managed_serviceaccount.token | length }}"
  - name: "Configure ServiceAccount RBAC for {{ managed_serviceaccount.name }}"
    ocmplus.cm.managed_serviceaccount_rbac:
      hub_kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"
      managed_cluster: "{{ hostvars[inventory_hostname].cluster_name }}"
      managed_serviceaccount_name: "{{ managed_serviceaccount.name }}"
      rbac_template: "{{ role_path }}/files/rbac"
      wait: True
      timeout: 60
    register: result
    ignore_errors: true
  - name: "Creating configMap {{ configmap_name }} on {{ hostvars[inventory_hostname].cluster_name }}"
    kubernetes.core.k8s:
      state: present
      host: "{{ cluster_proxy.cluster_url }}"
      validate_certs: no
      api_key: "{{ managed_serviceaccount.token }}"
      definition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: "{{ configmap_name }}"
    ignore_errors: true
  - name: "Removing managed ServiceAccount {{ managed_serviceaccount.name }}"
    ocmplus.cm.managed_serviceaccount:
      state: absent
      hub_kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"
      managed_cluster: "{{ hostvars[inventory_hostname].cluster_name }}"
      name: "{{ managed_serviceaccount.name }}"
      wait: True
      timeout: 60
