apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-all
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-get
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - pod
    verbs:
      - get
