apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-rolebinding
  namespace: default
roleRef:
  kind: Role
  name: configmap-all
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-rolebinding
  namespace: default
roleRef:
  kind: Role
  name: pod-get
